spring:
  application:
    name: employee-service
  datasource:
    url: jdbc:mysql://database-1.ctlrxrcqpjop.us-east-1.rds.amazonaws.com:3306/profile
    username: admin
    password: 12345678
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false

server:
  port: ${PORT:0}

services:
  auth:
    login: http://localhost:9999/auth/login

eureka:
  instance:
    hostname: localhost
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

