spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: sso-server
          uri: lb://sso-server
          predicates:
            - Path=/**
        - id: filter
          uri: lb://filter
          predicates:
            - Path=/filter/**
#        - id: composite-service
#          uri: lb://composite-service
#          predicates:
#            - Path=/composite-service/**

server:
  port: 9000

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
