spring:
  application:
    name: sso-server
  mvc:
    view:
      prefix: /
      suffix: .jsp
    servlet:
      path: /auth

  datasource:
    username: admin
    password: 12345678
    url: jdbc:mysql://database-1.ctlrxrcqpjop.us-east-1.rds.amazonaws.com:3306/profile
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 9999

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka
